development:
  adapter: postgresql
  encoding: unicode
  database: commentable-devise_development
  min_messages: WARNING
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: commentable-devise_test
  min_messages: WARNING
  pool: 5
